### ISSUE TITLE
Upgrade from ALTO v2 to v3

### ISSUE THREAD

**Issue by zuphilip** [altoxml/documentation#1]
Is it possible to automatically update ALTO v2 XML files to ALTO v3 XML files (or vice versa)? Since these are XML files I would expect some XSLT transformation for such a upgrade. Does there exist such an tools or XSLT file? Would it make sense to have some upgrade routines?

**Comment by cneud** [comment]
Since ALTO v2 XML files will not include any features introduced in ALTO v3 (or later), this should be as simple as changing the XML namespace declaration to the new namespace and schema location - e.g. via XSLT as below:

``` xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet 
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0"
   xmlns:v2="http://www.loc.gov/standards/alto/ns-v2#"
   xmlns:v3="http://www.loc.gov/standards/alto/ns-v3#">
   <xsl:template match="@* | node()">
      <xsl:copy>
         <xsl:apply-templates select="@* | node()"/>
      </xsl:copy>
   </xsl:template>

   <!-- replace xsi:schemaLocation attribute -->
   <xsl:template match="@xsi:schemaLocation">
      <xsl:attribute name="xsi:schemaLocation">http://www.loc.gov/standards/alto/ns-v3# http://www.loc.gov/standards/alto/v3/alto-3-0.xsd</xsl:attribute>
   </xsl:template>

   <!-- replace namespace  -->
   <xsl:template match="v2:*">
      <xsl:element name="{local-name()}" namespace="http://www.loc.gov/standards/alto/ns-v3#">
         <xsl:apply-templates select="@* | node()"/>
      </xsl:element>
   </xsl:template>

</xsl:stylesheet>
```

However, you might actually want to consider not "upgrading" these files, as not all software tools may support v3 just yet and there is no added benefit in introducing a v3 namespace in files that were produced using the v2 feature set - while it may cause errors from tools that expect v3 features under a v3 namespace.

**Comment by zuphilip** [comment]
Okay, thank you for the information. Yes, I agree that maybe currently there is not much advantage in upgrade existing ALTO v2 files to the new version, which is in simple using the new namespace (which might even break some tools).

We are currently collecting various transformations between different ocr-formats as well as validations of these, see http://digi.bib.uni-mannheim.de/ocr-schema/. I would like to provide as a much (meainingful) transformations as possible. Thus, I think the transformation between ALTO v2 and v3 would also fit there. The people using our tool do then have to decide, whether they want ALTO v2 or v3 maybe depending on their use case.

**Comment by Jo-CCS** [comment]
I think this topic is covered.
Thanks for sharing your transformation.
